# Generated by Django 5.1.4 on 2025-01-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_description", models.TextField()),
                ("post_image", models.ImageField(default=None, upload_to="")),
                ("post_like", models.IntegerField(default=0)),
                ("post_comments", models.TextField()),
            ],
        ),
    ]
